### ISSUE TITLE
Drag and Drop not working in Gutenberg

### ISSUE THREAD

**Issue by BenPav** [johannheyne/advanced-custom-fields-table-field#11]
With the new ACF gutenberg blocks, the Drag and Drop functionality is not working.,  Thanks

**Comment by johannheyne** [comment]
I can no longer reproduce the problem, but the drag and drop functionality is very inconvenient in my opinion. I will soon be replacing this with a newer one where the column or row to be moved is selected and then moved by clicking on an insertion point.
