### ISSUE TITLE
Error 500 - layout in layout

### ISSUE THREAD

**Issue by Triloworld** [johannheyne/advanced-custom-fields-table-field#12]
Not possible to use it in context of 2022 updates of WP, ACF and scenario provided.

We have this error: https://support.advancedcustomfields.com/forums/topic/custom-field-type-throws-fatal-error/#post-152860
Also we have 500 error in REST API and cannot save document.

Scenario to see error:
1. Add field table in:
This arrange:
- create "layout" field
-- in this "layout" create "repeater" field
--- in "repeater" create "table" field
For any pages and any number of fields, default setting.
2. Enter any page
3. Add one layout, one field in repeater and one table.
4. Try to save - get ERROR

Try without "repeater" and problem exist.
We test in many case and only layout in layout show error

**Comment by johannheyne** [comment]
Howdy,

you can download the newest version of the "Advanced Custom Fields: Table Field“ plugin under https://wordpress.org/plugins/advanced-custom-fields-table-field/

This may fixes the issues.

Cheers,
Johann

-- 
Johann Heyne, Web-Developer
+49 (0)351 6465728
***@***.***
Dresden, Germany
