### ISSUE TITLE
Feature Request: Preset Number of Columns / Rows

### ISSUE THREAD

**Issue by masteradhoc** [johannheyne/advanced-custom-fields-table-field#14]
Hi Johann

Thanks for this amazing plugin! One feature request from our side:
We'd love to have a setting inside ACF to preset the by default populated number of columns / rows.

Whats your opinion on this?

**Comment by johannheyne** [comment]
Hi,

thanks for the request.
I made a Pro version based on requests and am currently working on the website. I'm still struggling with all the licensing, tax and german business challenges, making the decision to use an online selling service or set the shop up myself.

You will be noticed by the free version of the plugin, when the Pro version is released.

Thanks,
Johann

**Comment by vinkla** [comment]
I highly recommend looking at https://lemonsqueezy.com/ for selling the pro version of the plugin.

**Comment by johannheyne** [comment]
Thanks a lot Vincent! Seems what I need and I will check it out.

**Comment by johannheyne** [comment]
Hi Brian,

thanks again for the tip with lemonsqueezy.com. The pro version has quietly gone online and may fits your feature request.
https://www.acf-table-field.com

Cheers, Johann
