### ISSUE TITLE
Table only fires a `change` event to ACF if a cell is edited. Doesn't update when only reordering, editing and deleting rows/columns

### ISSUE THREAD

**Issue by mrdarrengriffin** [johannheyne/advanced-custom-fields-table-field#18]
This is an issue I've seen many people raise with this plugin but without the insights into the actual issue. After quite a bit of debugging, I have found some useful things that hopefully @johannheyne can help explain, recreate the issue and hopefully fix.

I have a native ACF repeater field in which I have a table inside. From what I can tell, changes to the table will call `t.field_changed` function where it will only trigger a change event based on the field context.
https://github.com/johannheyne/advanced-custom-fields-table-field/blob/master/advanced-custom-fields-table-field/trunk/js/input-v5.js#L1288

Whilst editing the cell textarea fires its own event (that somehow tells ACF that the data has changed), reordering, adding and deleting rows/columns fires the `t.field_changed` function but with the `box` context. 

I had to put in a "hotfix" which allows both the `block` and `box` contexts to trigger the change event on the `obj_root` but it must be like this for a reason and deserves a proper fix.

A reliable way for me to tell whether updating the table has triggered a change event is to inspect the value of the hidden `_acf_changed` input (via `document.querySelector('#_acf_changed')` in the console). If the value is 1, then the table will update (presuming we only update the table to ensure the test is clean)

I'd really like this fixed as I used this as my go-to plugin for client builds and it would be a shame to stop using it. I will happily help any more details / debug info is needed but hopefully there is enough here for a fix to be added.

Thanks in advance!

**Comment by johannheyne** [comment]
Thanks for reporting me that issue, I will 
investigate and fix it now.

**Comment by johannheyne** [comment]
I was able to understand and reproduce the problem and fixed it in a prerelease.

As far as I understand, every change to the field must be announced with the trigger change if it is not recognized by ACF itself.

Here is a new version but not released yet. Maybe you can test whether this solves the problem for you too.
https://downloads.wordpress.org/plugin/advanced-custom-fields-table-field.1.3.22.zip

Cheers and Thanks a lot Darren!
Johann

**Comment by mrdarrengriffin** [comment]
Fantastic news. Thanks for the prompt response and taking the time to investigate it.

I will revert my hotfix and ensure the functionality breaks before testing the newer version. I'll get back to you shortly with the results

**Comment by mrdarrengriffin** [comment]
Hi @johannheyne.

After testing, this pre-release resolves the issue which is great news.

**Comment by mrdarrengriffin** [comment]
Fixed in 1.3.22
