### ISSUE TITLE
Add support for table footer (tfoot)

### ISSUE THREAD

**Issue by hacknug** [johannheyne/advanced-custom-fields-table-field#4]
Just like you allow users to add a table header, I think it would be great if the plugin also allowed for toggling on and off a table footer option.

Let me know what you think about this and if you'd be willing to take a PR to enable such functionality.

**Comment by johannheyne** [comment]
I´m going to release a Pro version including that functionality. But there is no release time yet.

**Comment by hacknug** [comment]
@johannheyne did you release it already?

**Comment by johannheyne** [comment]
Unfortunately not. I work whenever I can on it and it makes exiting progress. Thanks!
