### ISSUE TITLE
Table headers not shown

### ISSUE THREAD

**Issue by ideaweb** [johannheyne/advanced-custom-fields-table-field#9]
In acf-table-v5.php there is a check 

`$a['p']['o']['uh'] === 1`

but dumping the data it outputs

```
...
  ["p"]=>
  array(2) {
    ["o"]=>
    array(1) {
      ["uh"]=>
      string(1) "1"
    }
...
```

The comparisation fails and thats why no header is shown whatever is set.

Wordpress: 5.2.2
ACF: 5.8.2

**Comment by johannheyne** [comment]
Does the issue still exists? I tested it and "uh" is always a number.
